config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "flats#index"
  resources :flats
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  def index
    @flats = Flat.all
  end

  def show
  end

end

private

def set_flat
  @flat = Flat.find(params[:id])
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h2>Flats(<%=@flats.count%>)</h2>
<div class="main-container">
<div class = "cards">
<% @flats.each do |flat| %>
  <div class="card-trip">
  <img src="https://loremflickr.com/320/240/<%=flat.address.split(' ').last%>"/>
  <div class="card-trip-infos">
    <div>
      <h2><%=flat.name%></h2>
      <p><%=flat.description.first(200)%>...</p>
    </div>
  </div>
  <div class="card-trip-icones">
    <i class="fa-solid fa-people-line m-2"> <%=flat.number_of_guests%></i>
    <i class="fa-solid fa-money-bill-transfer m-2"> <%=flat.price_per_night%>€</i>
  </div>
  <div class="text-center mb-2">
    <strong><%= link_to "More infos", flat_path(flat) %></strong>
    <strong><%= link_to "Edit", flat_path(flat) %></strong>
    <strong><%= link_to "Remove", flat_path(flat) %></strong>
  </div>
  </div>
<% end %>
</div>
</div>

app/views/flats/show.html.erb
<div class="container mt-5">
<h2><%= @flat.name %></h2>
<p><%= @flat.address %></p>
<p><%= @flat.description %></p>
<p><%= @flat.price_per_night %></p>
<p><%= @flat.number_of_guests %></p>
<p><%= @flat.created_at %></p>

<%= link_to "Back to flat list", flats_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>